version: '3'
services:
  app:
    build: .   
    command: "unicorn"
    environment:
     - MONGODB_URI=${MONGODB_URI}

    ports:
      - "8080:8080"
  mongo:
    image: "mongo"

  nginx:
    image: "nginx"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
     - 80:80
     - 443:443
